-- T_COMN_LOGLEVEL: INSERT
INSERT IGNORE INTO `T_COMN_LOGLEVEL` (`PRIMARY_KEY`, `SERVICE_NAME`, `LOG_LEVEL`, `NOTE`, `DISUSE_FLAG`, `LAST_UPDATE_TIMESTAMP`, `LAST_UPDATE_USER`) VALUES ('24', 'ita-api-mcp-server', 'INFO', NULL, '0', CURRENT_TIMESTAMP, null);
