#
# https://docs.github.com/en/enterprise-cloud@latest/code-security/secret-scanning/configuring-secret-scanning-for-your-repositories#excluding-directories-from-secret-scanning-alerts-for-users
#
paths-ignore:
  - "ita_root/ita_job_etl/tests/db/exports/**"
  - "ita_root/ita_job_etl/pytest.ini.sample"
