-- Issue 2888: Conductor編集/作業実行に関係するデータサイズエラー解消
ALTER TABLE `T_COMN_CONDUCTOR_CLASS`
    MODIFY COLUMN `SETTING` LONGTEXT;
ALTER TABLE `T_COMN_CONDUCTOR_CLASS_JNL`
    MODIFY COLUMN `SETTING` LONGTEXT;
ALTER TABLE `T_COMN_CONDUCTOR_INSTANCE`
    MODIFY COLUMN `I_CLASS_JSON` LONGTEXT,
    MODIFY COLUMN `CLASS_JSON` LONGTEXT;
ALTER TABLE `T_COMN_CONDUCTOR_INSTANCE_JNL`
    MODIFY COLUMN `I_CLASS_JSON` LONGTEXT,
    MODIFY COLUMN `CLASS_JSON` LONGTEXT;
ALTER TABLE `T_COMN_CONDUCTOR_NODE_INSTANCE`
    MODIFY COLUMN `I_CONDUCTOR_CLASS_JSON` LONGTEXT,
    MODIFY COLUMN `I_MOVEMENT_JSON` LONGTEXT;
ALTER TABLE `T_COMN_CONDUCTOR_NODE_INSTANCE_JNL`
    MODIFY COLUMN `I_CONDUCTOR_CLASS_JSON` LONGTEXT,
    MODIFY COLUMN `I_MOVEMENT_JSON` LONGTEXT;