-- Issue#2937
UPDATE T_OASE_EVENT_TYPE SET EVENT_TYPE_NAME_JA = '2.新規イベント（統合予定）', EVENT_TYPE_NAME_EN = '2.New (consolidate)', LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE EVENT_TYPE_ID = '0020';

-- Issue#3006:
UPDATE T_COMN_MENU_COLUMN_LINK SET VALIDATE_OPTION = NULL, LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE COLUMN_DEFINITION_ID = '11011026';
UPDATE T_COMN_MENU_COLUMN_LINK SET VALIDATE_OPTION = NULL, LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE COLUMN_DEFINITION_ID = '11011027';
UPDATE T_COMN_MENU_COLUMN_LINK_JNL SET VALIDATE_OPTION = NULL, LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE COLUMN_DEFINITION_ID = '11011026';
UPDATE T_COMN_MENU_COLUMN_LINK_JNL SET VALIDATE_OPTION = NULL, LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE COLUMN_DEFINITION_ID = '11011027';