-- Issue #3006:
UPDATE T_COMN_MENU_COLUMN_LINK
SET VALIDATE_OPTION = NULL,
	LAST_UPDATE_TIMESTAMP = _____DATE_____
WHERE COLUMN_DEFINITION_ID = '11011026';

UPDATE T_COMN_MENU_COLUMN_LINK
SET VALIDATE_OPTION = NULL,
	LAST_UPDATE_TIMESTAMP = _____DATE_____
WHERE COLUMN_DEFINITION_ID = '11011027';

UPDATE T_COMN_MENU_COLUMN_LINK_JNL
SET VALIDATE_OPTION = NULL,
	LAST_UPDATE_TIMESTAMP = _____DATE_____
WHERE COLUMN_DEFINITION_ID = '11011026';

UPDATE T_COMN_MENU_COLUMN_LINK_JNL
SET VALIDATE_OPTION = NULL,
	LAST_UPDATE_TIMESTAMP = _____DATE_____
WHERE COLUMN_DEFINITION_ID = '11011027';
