-- Issue #2878 Terraform Cloud-EP Workspace管理にProject指定追加対応
ALTER TABLE T_TERE_WORKSPACE        ADD COLUMN PROJECT_NAME     VARCHAR(40)  AFTER ORGANIZATION_ID;
ALTER TABLE T_TERE_WORKSPACE_JNL    ADD COLUMN PROJECT_NAME     VARCHAR(40)  AFTER ORGANIZATION_ID;
