-- Issue #2878 Terraform Cloud-EP Workspace管理にProject指定追加対応
ALTER TABLE T_TERE_WORKSPACE        ADD COLUMN PROJECT_NAME     VARCHAR(40)  AFTER ORGANIZATION_ID;
ALTER TABLE T_TERE_WORKSPACE_JNL    ADD COLUMN PROJECT_NAME     VARCHAR(40)  AFTER ORGANIZATION_ID;

ALTER VIEW V_TERE_ORGANIZATION_WORKSPACE_LINK AS
SELECT
    TAB_B.ORGANIZATION_ID        ,
    TAB_B.ORGANIZATION_NAME      ,
    TAB_A.WORKSPACE_ID           ,
    TAB_A.WORKSPACE_NAME         ,
    CONCAT(TAB_B.ORGANIZATION_NAME,':',TAB_A.WORKSPACE_NAME) ORGANIZATION_WORKSPACE,
    TAB_A.TERRAFORM_VERSION      ,
    TAB_A.PROJECT_NAME           ,
    TAB_A.NOTE                   ,
    TAB_A.DISUSE_FLAG            ,
    TAB_A.LAST_UPDATE_TIMESTAMP  ,
    TAB_A.LAST_UPDATE_USER
FROM T_TERE_WORKSPACE TAB_A
LEFT JOIN T_TERE_ORGANIZATION TAB_B ON ( TAB_A.ORGANIZATION_ID = TAB_B.ORGANIZATION_ID )
;
ALTER VIEW V_TERE_ORGANIZATION_WORKSPACE_LINK_JNL AS
SELECT
    TAB_A.JOURNAL_SEQ_NO         ,
    TAB_A.JOURNAL_REG_DATETIME   ,
    TAB_A.JOURNAL_ACTION_CLASS   ,
    TAB_B.ORGANIZATION_ID        ,
    TAB_B.ORGANIZATION_NAME      ,
    TAB_A.WORKSPACE_ID           ,
    TAB_A.WORKSPACE_NAME         ,
    CONCAT(TAB_B.ORGANIZATION_NAME,':',TAB_A.WORKSPACE_NAME) ORGANIZATION_WORKSPACE,
    TAB_A.TERRAFORM_VERSION      ,
    TAB_A.PROJECT_NAME           ,
    TAB_A.NOTE                   ,
    TAB_A.DISUSE_FLAG            ,
    TAB_A.LAST_UPDATE_TIMESTAMP  ,
    TAB_A.LAST_UPDATE_USER
FROM T_TERE_WORKSPACE_JNL TAB_A
LEFT JOIN T_TERE_ORGANIZATION_JNL TAB_B ON ( TAB_A.ORGANIZATION_ID = TAB_B.ORGANIZATION_ID )
;

