DELETE FROM T_COMN_MENU WHERE MENU_GROUP_ID = "1201";
DELETE FROM T_COMN_MENU_JNL WHERE MENU_GROUP_ID = "1201";

DELETE FROM T_COMN_MENU_GROUP WHERE MENU_GROUP_ID = "1201";
DELETE FROM T_COMN_MENU_GROUP_JNL WHERE MENU_GROUP_ID = "1201";

DELETE FROM T_COMN_ROLE_MENU_LINK WHERE MENU_ID = "120101";
DELETE FROM T_COMN_ROLE_MENU_LINK_JNL WHERE MENU_ID = "120101";

DELETE FROM T_COMN_MENU_TABLE_LINK WHERE MENU_ID = "120101";
DELETE FROM T_COMN_MENU_TABLE_LINK_JNL WHERE MENU_ID = "120101";
