ALTER TABLE `T_COMN_OPERATION` ADD `ACCESS_PRIVILEGE` LONGTEXT NULL DEFAULT NULL AFTER `ENVIRONMENT`;
ALTER TABLE `T_COMN_OPERATION_JNL` ADD `ACCESS_PRIVILEGE` LONGTEXT NULL DEFAULT NULL AFTER `ENVIRONMENT`;
